repos:
  - repo: https://github.com/AmsterdamUMC-test/org-security-workflows
    rev: v0.1.0 # TODO: pin to a specific tag or commit hash for stability
    hooks:
      - id: check-forbidden-filetypes
        stages: [pre-commit]
      - id: check-forbidden-filetypes-prepush
        stages: [pre-push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=100"]
      - id: check-merge-conflict
