name: Org Security Scan
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  filetype-check:
    uses: AmsterdamUMC-test/org-security-workflows/.github/workflows/check-forbidden-filetypes.yml@main
    secrets: inherit

  personal-info-check:
    uses: AmsterdamUMC-test/org-security-workflows/.github/workflows/check-personal-info.yml@main
    secrets: inherit
